export const ERROR_401 = "ERROR_401"
export const ERROR_500 = "ERROR_500"

export const SET_LONGITUDE_LATITUDE = "SET_LONGITUDE_LATITUDE"
export const SET_LOCATION_INFO = "SET_LOCATION_INFO"
export const SET_CURRENT_ADDRESS = "SET_CURRENT_ADDRESS"
export const GET_LOCATION_LIST = "GET_LOCATION_LIST"

export const GET_ENTRIES_DATA = "GET_ENTRIES_DATA"
export const GET_RESTAURANTS = "GET_RESTAURANTS"
export const CLEAR_RESTAURANTS = "CLEAR_RESTAURANTS"
export const GET_FILTER_BAR = "GET_FILTER_BAR"

export const GET_TYPE_AHEAD = "GET_TYPE_AHEAD"
export const GET_HOT_SEARCH_WORDS = "GET_HOT_SEARCH_WORDS"

export const GET_SIFT_FACTORS = "GET_SIFT_FACTORS"
export const SET_CATEGORY_ID = "SET_CATEGORY_ID"
export const GET_CATEGORY = "GET_CATEGORY"
export const SET_SIFT_FACTORS = "SET_SIFT_FACTORS"
export const SET_MAIN_CATEGORY_ID = "SET_MAIN_CATEGORY_ID"